version: '3.7'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: always

  user-service:
    restart: always
    build: ./
    working_dir: /app
    expose:
      - "8089"
    depends_on:
      - mysql
    command: gradle clean bootRun -Dspring-boot.run.profiles=docker



